### ISSUE TITLE
Imaginary time evolution

### ISSUE THREAD

**Issue by AlexSchuckert** [GregDMeyer/dynamite#11]
Hi,

thanks for this amazing library! Is it possible to choose imaginary times in evolve()? Together with typicality (i.e. averaging over Haar random initial states), this would enable computations of finite temperature expectation values. 

Alex

**Comment by GregDMeyer** [comment]
glad you are enjoying it! You should be able to just directly pass an imaginary time to evolve() --- e.g. you can do

```H.evolve(-1j*tau)  # just be careful about getting the sign right```

let me know if you have any issues with it! :)  We actually have a paper where dynamite was used in this way, relying on typicality, see: https://arxiv.org/abs/2002.05725

cheers!

**Comment by AlexSchuckert** [comment]
HI Greg,

Awesome, thanks a lot! I'll make sure to cite your paper if I use your
code.

Best
Alex

Am Mo., 23. März 2020 um 20:10 Uhr schrieb Greg Meyer <
notifications@github.com>:
