### ISSUE TITLE
eigensolve with mpirun

### ISSUE THREAD

**Issue by sameersheorey** [GregDMeyer/dynamite#16]
Hi Greg,

Is the function `dynamite.computations.eigsolve` designed for multiprocessing? If I run:

```
    energies_start = time.time()
    energies = H.eigsolve(nev=n_ev)
    energies_end = time.time()
``` 
With for example `mpirun -n 10 python my_script.py` it seems to run slower than just `python my_script.py`. 

Thanks
Sam

**Comment by sameersheorey** [comment]
Thanks for the reply Greg! Indeed when using more spins I found a significant speedup when using two processors. Using more than two however resulted in a slow down. Do you know why this could be? I ran:

```
from functions import *
from dynamite import config

config.shell = True

n = 18

H_start = time.time()
H = syk_hamiltonian_fast(n)
H_end = time.time()
H_time = H_end - H_start

mpi_print('H build time', H_time)

energies_start = time.time()
energies = H.eigsolve(nev=100)
energies_end = time.time()
energies_time = energies_end - energies_start

mpi_print('find evalue time', energies_time )
```

with results 

```
k1920550@erc-hpc-login1:~$ singularity exec docker://gdmeyer/dynamite python spectrum.py
INFO:    Using cached SIF image
H build time 0.4464128017425537
find evalue time 7.762933969497681
k1920550@erc-hpc-login1:~$ singularity exec docker://gdmeyer/dynamite mpirun -n 2 python spectrum.py
INFO:    Using cached SIF image
H build time 0.3703474998474121
find evalue time 1.876288652420044
k1920550@erc-hpc-login1:~$ singularity exec docker://gdmeyer/dynamite mpirun -n 3 python spectrum.py
INFO:    Using cached SIF image
H build time 0.4385504722595215
find evalue time 84.5620219707489
```

Thanks
Sam

**Comment by GregDMeyer** [comment]
Ah---I think the main thing I would try is the following: the parallel solves are much faster with power-of-two numbers of ranks. See if you get a speedup with 4 ranks! Also, I think L=18 is probably still a bit small---maybe try 20 if 4 ranks doesn't do it! Let me know what you find! :-)

**Comment by sameersheorey** [comment]
I tried n=20 and n=22 and unfortunately no luck. For n=22 I found (I quit the run with 4 ranks after around 10 mins):
```
k1920550@erc-hpc-login2:~$ singularity exec docker://gdmeyer/dynamite:latest-int64 mpirun -n 1 python spectrum.py 22
INFO:    Using cached SIF image
H build time 0.807631254196167
find evalue time 48.123520851135254
k1920550@erc-hpc-login2:~$ singularity exec docker://gdmeyer/dynamite:latest-int64 mpirun -n 2 python spectrum.py 22
INFO:    Using cached SIF image
H build time 1.475696086883545
find evalue time 139.04376363754272
k1920550@erc-hpc-login2:~$ singularity exec docker://gdmeyer/dynamite:latest-int64 mpirun -n 4 python spectrum.py 22
INFO:    Using cached SIF image
H build time 6.399624586105347
```

I've been testing this in the login node for our cluster so maybe this is the issue? However, when I try to run a batch job on the cluster cpu nodes mpirun doesn't seem to work. I contacted the cluster support team who suggested the issue appears to be with the docker image so I should contact you about it. The error I get is:

```
INFO:    Using cached SIF image
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: General MPI error
[0]PETSC ERROR: MPI error 1 MPI_ERR_BUFFER: invalid buffer pointer Ignore the following value 38
[0]PETSC ERROR: See https://petsc.org/release/faq/ for trouble shooting.
[0]PETSC ERROR: Petsc Release Version 3.17.3, Jun 29, 2022
[0]PETSC ERROR: Unknown Name on a complex-opt named erc-hpc-comp009 by k1920550 Fri Jul  8 12:15:04 2022
[0]PETSC ERROR: Configure options --with-debugging=0 --with-fortran-kernels=1 --COPTFLAGS=-O3 --CXXOPTFLAGS=-O3 --FOPTFLAGS=-O3 --with-scalar-type=complex --with-64-bit-in>
[0]PETSC ERROR: #1 PetscOptionsInsert() at /opt/petsc/src/sys/objects/options.c:838
[0]PETSC ERROR: #2 PetscInitialize_Common() at /opt/petsc/src/sys/objects/pinit.c:933
[0]PETSC ERROR: #3 PetscInitialize() at /opt/petsc/src/sys/objects/pinit.c:1224
Traceback (most recent call last):
  File "/users/k1920550/spectrum.py", line 14, in <module>
    mpi_print('H build time', H_time)
  File "/venv/lib/python3.9/site-packages/dynamite/tools.py", line 13, in mpi_print
    config._initialize()
  File "/venv/lib/python3.9/site-packages/dynamite/__init__.py", line 85, in _initialize
    slepc4py.init(slepc_args)
  File "/venv/lib/python3.9/site-packages/slepc4py/__init__.py", line 44, in init
    PETSc._initialize(args)
  File "PETSc/PETSc.pyx", line 494, in petsc4py.PETSc._initialize
  File "PETSc/PETSc.pyx", line 396, in petsc4py.PETSc.initialize
petsc4py.PETSc.Error: error code 98
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[6822,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

The python script spectrum.py was the one from my previous comment.

Do you know what could be going wrong here?
Thanks again for your help!
Sam

**Comment by GregDMeyer** [comment]
Ah, I think you're right that you aren't getting great performance because you are on the login node. The MPI issue is because the version of MPI in the image doesn't match the one on the cluster. I think the easiest way for you to use it on the cluster would probably be to build dynamite there yourself. You can follow the instructions here: https://dynamite.readthedocs.io/en/latest/install.html It should be pretty straightforward!

Let me know how it goes!

**Comment by sameersheorey** [comment]
Okay thanks for letting me know, I will have a go!

**Comment by GregDMeyer** [comment]
Hi Sam! I just remembered one more trick---try setting the environment variable OMP_NUM_THREADS to 1. Sometimes OpenMP tries to use the extra cores but they get shared between the various MPI processes and it kills performance. Let me know if this helps!

**Comment by sameersheorey** [comment]
Thanks for the suggestion! Unfortunately this doesn't seem to have affected the performance
```
k1920550@erc-hpc-login2:~$ OMP_NUM_THREADS=1 singularity exec docker://gdmeyer/dynamite:latest-int64 mpirun -n 2 python spectrum.py 20
INFO:    Using cached SIF image
H build time 1.463839054107666
find evalue time 25.39880061149597
k1920550@erc-hpc-login2:~$ singularity exec docker://gdmeyer/dynamite:latest-int64 mpirun -n 2 python spectrum.py 20
INFO:    Using cached SIF image
H build time 1.4833083152770996
find evalue time 26.201353311538696
k1920550@erc-hpc-login2:~$ OMP_NUM_THREADS=1 singularity exec docker://gdmeyer/dynamite:latest-int64 mpirun -n 8 python spectrum.py 20
INFO:    Using cached SIF image
H build time 13.892127990722656
^C
```

Hopefully installing from source will do the trick, I've managed to install onto my laptop but running into an issue when trying to install on the cluster. Hopefully can work it out soon.

**Comment by sameersheorey** [comment]
Hi Greg, I still need to get the source installation to work on the cluster but mpi run does give a speedup when used on the desktop/laptop so will close this issue. Before I do I have one quick question - does the GPU support only work on a machine with an Nvidia GPU or would it work on a Mac Pro which has AMD Radeon Pro? Sorry for the naive question!

**Comment by GregDMeyer** [comment]
OK, sounds good! I hope the source install goes smoothly (it usually is quite easy to get set up, if that gives you any encouragement). 

Unfortunately for now the GPU support relies on CUDA, which is proprietary to nvidia---however moving towards a vendor-agnostic implementation of GPU support is something that is certainly on our radar! Unfortunately it probably won't happen particularly soon due to it being a sizable project and other stuff being higher on the to-do list.

**Comment by sameersheorey** [comment]
Okay thanks!
